import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import listingsRouter from "./listings";
import nearbyListingsRouter from "./nearby-listings";
import chatRouter from "./chat";
import usersRouter from "./users";
import notificationsRouter from "./notifications";
import announcementsRouter from "./announcements";
import adminRouter from "./admin";
import supportRouter from "./support";
import parttimeRouter from "./parttime";
import sourcesRouter from "./sources";
import pendingJobsRouter from "./pending-jobs";
import telegramAuthRouter from "./telegram-auth";
import pushRouter from "./push";
import managementTeamRouter from "./management-team";
import chatBannersRouter from "./chat-banners";
import knownCompaniesRouter from "./known-companies";
import companyProfilesRouter from "./company-profiles";
import locationAdminRouter from "./location-admin";
import moderatorRouter from "./moderator";
import publisherVerifyRouter from "./publisher-verify";
import { whatsappRouter } from "../modules/whatsapp";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(nearbyListingsRouter);
router.use(listingsRouter);
router.use(chatRouter);
router.use(usersRouter);
router.use(notificationsRouter);
router.use(announcementsRouter);
router.use(adminRouter);
router.use(publisherVerifyRouter);
router.use(locationAdminRouter);
router.use("/moderator", moderatorRouter);
router.use(supportRouter);
router.use(parttimeRouter);
router.use(sourcesRouter);
router.use(whatsappRouter);
router.use(pendingJobsRouter);
router.use(telegramAuthRouter);
router.use(pushRouter);
router.use(managementTeamRouter);
router.use(chatBannersRouter);
router.use(knownCompaniesRouter);
router.use(companyProfilesRouter);

export default router;
